### ISSUE TITLE
Version 6 for Infinispan and Hazelcast

### ISSUE THREAD

**Issue by hc-codersatlas** [vladimir-bukhtoyarov/bucket4j#144]
Hi, is there a version 6 release for Hazelcast and Infinispan? They're not in Jcenter or Maven. Do we use 4.10 + 6.0 of jcache / core?

Thanks!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @hc-codersatlas 

I've found the mistake in the release procedure. But I can not fix it until 13 January, because I am traveling now and I have no access to my release environment. 
So you have two options:
* Just wait for 13 January
* Or build missed artifacts from sources(master or 6.0 branch)

**Comment by hc-codersatlas** [comment]
Sure thanks, please update when you can.

**Comment by vladimir-bukhtoyarov** [comment]
Missed artefacts have been deployed
