### ISSUE TITLE
I have a qq-- is this open source and available to use free ? means no change. 

### ISSUE THREAD

**Issue by pradeepkusingh** [vladimir-bukhtoyarov/bucket4j#2]

**Comment by vladimir-bukhtoyarov** [comment]
Hello. 

Bucket4j is absolutely open, You are free to use or fork. Let me know if you have problem with documentation, I will try to explain. Or if something functionality is missed for you I will try to enhance.

**Comment by pradeepkusingh** [comment]
this is not working as expected.

Bucket bucket = Buckets.withNanoTimePrecision()
    .withLimitedBandwidth(1000, TimeUnit.HOURS, 1)
    .withGuaranteedBandwidth(1, TimeUnit.MINUTES, 10)
    .build();

This is let go mor than 1000 request in an hour.

**Comment by vladimir-bukhtoyarov** [comment]
You observe bursting effect which happens when bucket is cold(fullfilled). [Token bucket algorithm](https://en.wikipedia.org/wiki/Token_bucket) allows bursting by design, because there is no way to implement compact and hight effective solution without bursting.

With configuration which you provided - for first hour it is possible to consume 1000*2 = 2000 tokens, where:
- First 1000 tokens - is the initial size of bucket.
- Second 1000 tokens - is the refilled count for a hour.

You can minimize bursting effect via adding restriction with higher granularity. For example 20 tokens for minute:
``
Bucket bucket = Buckets.withNanoTimePrecision()
                .withLimitedBandwidth(1000, TimeUnit.HOURS, 1)
                .withLimitedBandwidth(20, TimeUnit.MINUTES, 1)
                .withGuaranteedBandwidth(1, TimeUnit.MINUTES, 10)
                .build();
``

Configuaration above provide guarantee that no more then 1020 token can be consumed for one hour.

**You should pay double attention** to the fact that if bursting is strongly not allowed then you should not use bucket4j or any other solution implemented across leaky bucket ideas, because only one suitable solution in this case would be storing each event about issuing token for a one hour, then invalidate event when it expired. For example you can use something like this:
``
import java.util.LinkedList;

public class AbsolutelyPrecisionLimiter {

    private long currentTokens;
    private final long periodMillis;

    private LinkedList<Permit> issuedTokens = new LinkedList<>();

    public AbsolutelyPrecisionLimiter(long maxTokens, long periodMillis) {
        this.currentTokens = maxTokens;
        this.periodMillis = periodMillis;
    }

    public boolean tryConsume(int tokens) {
        synchronized(this) {
            long nowMillis = System.currentTimeMillis();

            // clearing obsolete values
            while (true) {
                Permit permit = issuedTokens.getFirst();
                if (nowMillis - permit.timestampMillis > periodMillis) {
                    currentTokens += permit.tokens;
                    issuedTokens.removeFirst();
                } else {
                    break;
                }
            }

            if (currentTokens < tokens) {
                // has no required tokens
                return false;
            }

            currentTokens -= tokens;
            issuedTokens.addLast(new Permit(tokens, nowMillis));
            return true;
        }
    }

    private static final class Permit {
        private final long tokens;
        private final long timestampMillis;

        private Permit(long tokens, long timestampMillis) {
            this.tokens = tokens;
            this.timestampMillis = timestampMillis;
        }
    }
}
``
Moreover for case 1000 tokens per hour structure above will consume about 32Kb(versus), this is not a big memory size. However solutions like AbsolutelyPrecisionLimiter in common case can consume too much memory, for example 1 million tokens per hour. So there is trade-off: absolutely precision  versus resources which we able to wast to satisfy absolutely precision. I believe that for many cases it is enough to configure fine-granulated bandwidth for bucket and agree with bursting with something can happen.

If you provide more information about the problem you are trying to solve then I can help you more.

**Comment by vladimir-bukhtoyarov** [comment]
Also to satisfy limitation 1000 tokens per hour you can use following a little bit tricking solutions:

``` java
Bucket bucket = Buckets.withNanoTimePrecision()
                .withLimitedBandwidth(500, TimeUnit.MINUTES, 30)
                .build();
```
Configuration above provides guarantees to 1000 tokens per hour independent of bursting.
