### ISSUE TITLE
Distributed Environment example with Hazelcast and spring boot for Client side

### ISSUE THREAD

**Issue by Rajesh-satan** [vladimir-bukhtoyarov/bucket4j#205]
I want to rate limit a call to a client url and I have two instances of the my API.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Rajesh-satan 

1. Just read a [few examples](https://bucket4j.com/7.0.0/toc.html#quick-start-examples) that show how to use Bucket4j in a none-clustered environment.

2. Do you know how to start Hazelcast cluster? If no then read [official Hazelcast documentation](https://docs.hazelcast.com/home/)

3. When you are able to create Cache just follow these instructions about [bucket4j-hazelcast integration](https://bucket4j.com/7.0.0/toc.html#bucket4j-hazelcast).

4. Also if asynchronous API is not required then you can choose [bucket4j-jcache integration](https://bucket4j.com/7.0.0/toc.html#bucket4j-jcache) instead of ```bucket4j-hazelcast```.

**Comment by Rajesh-satan** [comment]
@vladimir-bukhtoyarov Thank you
