### ISSUE TITLE
Redis backend support

### ISSUE THREAD

**Issue by robertmircea** [vladimir-bukhtoyarov/bucket4j#36]
Any chance to support Redis as backing store for limits?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @robertmircea 

I have no motivation to add this feature to bucket4j, because Redis does not intersect with my career. I have no technical competency in Redis, I never used it before and most likely will not use it in nearest future. So, in nearest time, I do not plan to add Redis as back-end for bucket4j. 

Today, I did a quick investigation of Redis features, and I found that it provides all necessary functionality to  implement back-end for bucket4j in effective way:
1. Redis has transactions, and this allow to implement token-bucket correctly in concurrent environment.
2. Redis has stored procedures on Lua. This enough to handle any limiting request via single network hop, similar to JCache.

In the theory, Redis backend will have good performance. I do not believe that performance will be so good like with JCache backends like Hazelcast or Ignite, but it will be interesting to compare performance of Redis with performance of VoltDb. I have plans to implement the support of VoltDb at august, and may be, I will add support for Redis in the end of this year, if no other interesting challenges(directly related with my experience) will happen.

**Comment by taasjord** [comment]
Redisson has a JCache adapter to Redis, which I have tested and found to be working with Bucket4j JCache integration. I am a bit unsure about its performance though, as I multiple Redis commands issued per request (mind you I have little insight in Redis).  With a single local Redis instance I get about 10-15 ms overhead per request. Obviously there will be some overhead with a distributed persistence, but I don't know what to expect and how the other JCache backends perform.

A sidenote on using a distributed cache: for optimal performance it would be super nice to have an option to use an in-memory cached instance of bucket values, and only reconcile with the distributed cache in the background.

**Comment by vladimir-bukhtoyarov** [comment]
I thinks that that 10-15 ms overhead per request is not suitable for most users. For example when using any JCache implementation directly we have a latency 1ms(and less).

>  I am a bit unsure about its performance though, as I see multiple Redis commands issued per request.

And that is why I plan to implement native support for Redis via Lua scripts, and that will allow achieve mostly similar(I hope) performance with JCache, because will require only one network round-trip. Also, the multiple calls per one request was reason why [universal support for relational databases](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/18) was declined and replaced by plans to support each particular database directly [PostgreSQL issue 38](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/38), [MySQL issue 37](https://github.com/vladimir-bukhtoyarov/bucket4j/issues/37), 
DBMS specific stored procedures will allow to always handle throttling request in one call to database.

> A sidenote on using a distributed cache: for optimal performance it would be super nice to have an option to use an in-memory cached instance of bucket values, and only reconcile with the distributed cache in the background.

It is hard to implement correctly this strategy (see for example this discussion #8 ). I suppose that if Redis backend will act with 1-1,5 ms latency, then so complex optimization will be not needed.

**Comment by vladimir-bukhtoyarov** [comment]
Most likely it would be nice to use [luna](https://github.com/kroepke/luna) for unit testing of stored procedures.

**Comment by cesartl** [comment]
For reference I want to add that with @vladimir-bukhtoyarov's help, I have verified that Redisson is not an appropriate `JCache` implementation for Bucket4j. Although it seems to the working fine, it actually doe not respect the bucket policy. This is because Redisson does not invoke `EntryProcessor` in isolation (credit to Validimir for finding this out). If you test the implementation with enough concurrency you should start to notice the policy violations.

Here is a test that Vladimir wrote to exhibit this issue:

```java
import javax.cache.Cache;
import javax.cache.processor.EntryProcessor;
import java.util.concurrent.CountDownLatch;

public class CompatibilityTest {

    final Cache<String, Integer> cache;


    public CompatibilityTest(Cache<String, Integer> cache) {
        this.cache = cache;
    }

    public void test() throws InterruptedException {
        String key = "42";
        int threads = 4;
        int iterations = 1000;
        cache.put(key, 0);
        CountDownLatch latch = new CountDownLatch(threads);
        for (int i = 0; i < threads; i++) {
            new Thread(() -> {
                try {
                    for (int j = 0; j < iterations; j++) {
                        EntryProcessor<String, Integer, Void> processor = (mutableEntry, objects) -> {
                            //race condition happens here
                            int value = mutableEntry.getValue();
                            mutableEntry.setValue(value + 1);
                            return null;
                        };
                        cache.invoke(key, processor);
                    }
                } finally {
                    latch.countDown();
                }
            }).start();
        }
        latch.await();
        int value = cache.get(key);
        if (value == threads * iterations) {
            System.out.println("Implementation which you use is compatible with Bucket4j");
        } else {
            String msg = "Implementation which you use is not compatible with Bucket4j";
            msg += ", " + (threads * iterations - value) + " writes are missed";
            throw new IllegalStateException(msg);
        }
    }

}
```

**Comment by vladimir-bukhtoyarov** [comment]
@taasjord did you tested high-contended scenarios? If, so which settings for cache did you use? It looks like with default setting Redisson is not compatible with Bucket4j.

**Comment by taasjord** [comment]
@vladimir-bukhtoyarov, it was just a simple test with a few requests. 

I followed docs here:  https://github.com/redisson/redisson/wiki/14.-Integration%20with%20frameworks#144-jcache-api-jsr-107-implementation

Here are my redisson-jcache.yaml settings:

```
singleServerConfig:
  address: "redis://127.0.0.1:6379"
  connectTimeout: 1000
  timeout: 3000
codec: !<org.redisson.codec.SerializationCodec> {} 
```
The codec was necessary to specify, because the default didn't work.

**Comment by jjzabkar** [comment]
I spent a lot of time trying to get Bucket4j to work with Redis; in the end, the out-of-the-box setup for [RateLimitJ](https://github.com/mokies/ratelimitj/tree/master/ratelimitj-redis) took only minutes to work successfully.

**Comment by cesartl** [comment]
@jjzabkar did you validate that RateLimitJ + Redis works on a multi-node environment? i.e. when you have multiple clients sharing the same resource and editing concurrently?

**Comment by cesartl** [comment]
In my case I wrote a simple bash script to have multiple threads making request to an endpoint with a limit on the rate and make sure that overall the limit is not broken. This wasn't successful with Redis because JCache implementation does not ensure atomicity in a cache update operation (`EntryProcessor`)

**Comment by vladimir-bukhtoyarov** [comment]
@cesartl Ratelimit4j uses stored procedures on lua, thus Reddison or any other Redis->JCache bridge is not used, so Ratelimit4j has no problems with concurrency.  The way of Ratelimit4j is only one right way to implement rate-limiting on top of Redis, I already mentioned that at start of  this topic https://github.com/vladimir-bukhtoyarov/bucket4j/issues/36#issuecomment-309240092

Eventually I will add support for Redis on top of Lua stored procedures. But it will not be soon, because I heavily use Apache Ignite on my Job, and any JCache implementation provides better benifits for Java developers than Redis, so I have no motivation to add support Redis asap. Maybe in April 2018, if I will have enough free time to learn something new like Redis.

**Comment by vladimir-bukhtoyarov** [comment]
@cesartl so, if you want to use Redis to solve reate-limiting challenge(I really do not understand why to prefer it over JCache, but I see that you spent significant time to conquer Redis) than I recommend to use RateLimitJ. I just will notify you when Bucket4j support for Redis will be done.

**Comment by cesartl** [comment]
@vladimir-bukhtoyarov ho no I've been using Hazelcast since we found the problem with Redis :)
So I'm still using Bucket4J!

**Comment by vladimir-bukhtoyarov** [comment]
Since we need in async support the [Lettuce](https://github.com/lettuce-io) choosen as redis driver.

**Comment by vladimir-bukhtoyarov** [comment]
All necessary properties of Redis transactions have been successfully tested via [LuaScriptIsolationTest](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/redis_compatibility_test/experimental/bucket4j-redis/src/test/java/compatibility_test/LuaScriptIsolationTest.java)

The implementation of Redis support will be launched in June 2018.

**Comment by nareshbaliga** [comment]
@vladimir-bukhtoyarov Did native Redis support make it to a release?

**Comment by vladimir-bukhtoyarov** [comment]
This feature is in the middle of progress.

**Comment by user404d** [comment]
Took the time to spike out redis integration using the changes staged in the 5.0 branch. If anyone's interested you can take a look at #102

**Comment by theflippedbit** [comment]
@vladimir-bukhtoyarov how stable is the experimental implementation of this to use (in `experimental/bucket4j-redis/`)? Thanks!

**Comment by vladimir-bukhtoyarov** [comment]
@theflippedbit there is no working version for Redis.

**Comment by theflippedbit** [comment]
@vladimir-bukhtoyarov hehe I actually just looked into bucket4j-redis and realized that it's practically empty besides tests :D I realize it's not a priority, but is there any chance that redis support will be added?

**Comment by vladimir-bukhtoyarov** [comment]
eventully, Redis support will be added

**Comment by ph4r05** [comment]
@vladimir-bukhtoyarov Github recently announced they migrated rate limiters from Memcached to Redis backend: https://github.blog/2021-04-05-how-we-scaled-github-api-sharded-replicated-rate-limiter-redis/

The post also contains Lua scripts that atomically manage it atomically. I thought it might be helpful.

**Comment by jonathannaguin** [comment]
@vladimir-bukhtoyarov  do you think you will be able to release the 7.x version any time soon?

**Comment by vladimir-bukhtoyarov** [comment]
Yes. see this comment https://github.com/vladimir-bukhtoyarov/bucket4j/discussions/161#discussioncomment-594410

**Comment by morj** [comment]
Hi! Thanks a lot for the redis support.

Just a quick question: do I need to use `6.4.1` version for stable redis backend, or should I wait for 7.X.X non-beta in maven?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @morj 

There is no support for Redis inside 6.x
So, there there are no alternatives for waiting for 7.0.0

Moreover, the proposed solution in the 7.x beta needs to be rewritten because as mentioned in this comment https://github.com/vladimir-bukhtoyarov/bucket4j/discussions/161#discussioncomment-1165086 RMap is not a suitable data structure. 

So most likely I will exclude the support for Redis from the upcoming 7.0 release. It means that Bucket4j does not provide Redis Support currently, and will not provide such support in the nearest future.

**Comment by jason076** [comment]
Is the currently implemented Redis support usable for Production. As I can see in https://github.com/vladimir-bukhtoyarov/bucket4j/blob/5ee3d17a17ca32843e0ad12cff35c92598b8b01f/bucket4j-redis/src/main/java/io/github/bucket4j/redis/redisson/cas/RedissonBasedProxyManager.java you have updated the implementation since your last post and redis support ist stated in the 7.0.0 release notes https://bucket4j.com/7.0.0/release-notes.html . But redis support ist not mentioned in the readme and this issue ist still open, so I am wondering if it is ready to use?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @jason076,

I had a lack of time to document integration with Redis. I suppose that the current implementation is good to be used in production.

**Comment by jason076** [comment]
Hi @vladimir-bukhtoyarov,
cool, that are great news. Thank you for your quick reply and especially for your work.

**Comment by bagdemir** [comment]
I have just created a blog post about Token Buckets with Redis by using Bucket4J in a Spring Boot application. https://medium.bitwise.blog/rate-limiting-with-token-buckets-7f912525819f
I hope it helps.

**Comment by vladimir-bukhtoyarov** [comment]
@bagdemir  thank you
