### ISSUE TITLE
Possible unsafe BucketState cloning?

### ISSUE THREAD

**Issue by MrNghia123** [vladimir-bukhtoyarov/bucket4j#40]
Hi,
I noticed the usages of the following BucketState methods in the LockFreeTokenBucket implementations.
I wonder if the cloning / copy of array in Java is atomic? Otherwise could the non-atomicity make  LockFreeTokenBucket unsafe?

public BucketState copy() {
   return new BucketState(stateData.clone());
}
public void copyStateFrom(BucketState sourceState) {
  System.arraycopy(sourceState.stateData, 0, stateData, 0, stateData.length);
}

**Comment by vladimir-bukhtoyarov** [comment]
Hi,

**arraycopy** does not act in atomic way, but there is no problem, because array is effectively immutable:
- Algorithm behind non-blocking implementation never modifies array after succesfull CAS, any thread which want to modify array, does copying and modifies the copy which is local and not shared between other threads.
- All mutations done when array is not visible to other threads.
- All mutation happen with arrary, always are completely visible to another threads, because reading of state happens during volatile read(through AtomicReference).
