### ISSUE TITLE
New a method to get current rate setting for JCache/Hazelcast integration.

### ISSUE THREAD

**Issue by kchenhal** [vladimir-bukhtoyarov/bucket4j#53]
Right now the Bucket.getConfiguration() only return the value provided in configuration Supplier. it did not reflect the true setting when integrated with JCache, or Hazelcast.

**Comment by vladimir-bukhtoyarov** [comment]
```getConfiguration``` method removed from bucket interface in order to avoid undefined behavior. Instead following ways added:
- New interface [LocalBucket](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.1/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java) with method [getConfiguration](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.1/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L16) for local useage scenarios
- New method [getProxyConfiguration](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/3.1/bucket4j-core/src/main/java/io/github/bucket4j/grid/ProxyManager.java#L68) in ```ProxyManager``` for distributed usage scenarios.

**Comment by vladimir-bukhtoyarov** [comment]
@kchenhal please provide feedback for #53 and #54 using following dependency
```xml
<dependency>
    <groupId>com.github.vladimir-bukhtoyarov</groupId>
    <artifactId>bucket4j-core</artifactId>
    <version>3.1.0-rc1</version>
</dependency>
```
If all will work fine for you then I will release version 3.1.0

**Comment by vladimir-bukhtoyarov** [comment]
released!
