### ISSUE TITLE
Implement support of kotlin coroutines for asyncronous API

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [vladimir-bukhtoyarov/bucket4j#55]
It would be nice to have direct support of [coroutines](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md) at library level.

**Comment by vladimir-bukhtoyarov** [comment]
Kotlin corutines [have support for CompletableFuture](https://github.com/Kotlin/kotlin-coroutines/blob/master/examples/future/future-example.kt) out of the box, so implementation of this issue has no sense

**Comment by malaquf** [comment]
Hello @vladimir-bukhtoyarov, first of all, thank you for providing such great and useful lib!

I've used in java projects and everything works very well. However, I just came across this issue because I have the same struggle with Kotlin projects. I'm not sure if I understood your proposal correctly on your comment above closing this issue, but if I understood it right, you are suggesting to wrapping the calls in suspended calls, right?

However, this doesn't solve the problem. The great thing about kotlin coroutines is that it doesn't creates IO overhead with threads. Wrapping the execution in a CompletableFuture would still create overhead. Unfortunately, it looks like only [Lettuce client](https://redis.github.io/lettuce/user-guide/kotlin-api/) supports coroutines, and therefore, yes, for other drivers it probably still doesn't make sense to implement it.

I wonder if it'd make more sense to start a new project for a kotlin native "bucket4j" library or extending this one.

What are your thought on this?

Thank you!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @malaquf 

I do not understand what kind of overhead you are talking about. Ability of underlying technology to use NIO does not depend from the language in which client was written. CompletableFuture is standart way in which NIO based solutions like Hazelcast/Ignite/Letucce/etc expose its API, so Bucket4j doing the same in same way.

**Comment by malaquf** [comment]
Hi @vladimir-bukhtoyarov. Thank you for the fast answer!

Yes, while it is true that the implementation from bucket4J uses async calls from lettuce(for eg), [tryConsume](https://github.com/bucket4j/bucket4j/blob/d7aa6744afdf39dcb1b83abcbc06a26631adff50/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L70) is blocking from the application point of view, and requires additional wrapping to make it properly async, otherwise it would still hold app container's threads (in Kotlin, something like [this](https://github.com/ksletmoe/Bucket4k/blob/mainline/src/main/kotlin/com/sletmoe/bucket4k/SuspendingBucketImpl.kt#L26)).

Therefore, I was wondering if it would be interesting to have such support directly in the lib, or maybe even have a kotlin native one.

**Comment by vladimir-bukhtoyarov** [comment]
> Yes, while it is true that the implementation from bucket4J uses async calls from lettuce(for eg), [tryConsume](https://github.com/bucket4j/bucket4j/blob/d7aa6744afdf39dcb1b83abcbc06a26631adff50/bucket4j-core/src/main/java/io/github/bucket4j/Bucket.java#L70) is blocking from the application point of view

Why do you point to synchronous API and clime that it is synchronous? Did you read this [Asynchronous API](https://bucket4j.com/8.14.0/toc.html#asynchronous-api)?

**Comment by malaquf** [comment]
Obviously because I haven't seen it! :)
That solves my question. Thank you!

**Comment by malaquf** [comment]
I've just implemented it and ofc it works like a charm! Thank you!
