### ISSUE TITLE
Dependency on Oracle jar makes it very hard to use bucket4j

### ISSUE THREAD

**Issue by stevenschlansker** [vladimir-bukhtoyarov/bucket4j#9]
Currently bucket4j ships with a `system` scope dependency on Oracle Coherence.
This jar is not publicly available.  The build notes issues:
```
[WARNING] Some problems were encountered while building the effective model for com.github:bucket4j:jar:1.1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for com.oracle:coherence:jar should not point at files within the project directory, ${project.basedir}/lib/coherence-3.7.1.5.jar will be unresolvable by dependent projects @ line 268, column 25
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
```
Indeed, attempting to use the library causes problems:
```
[ERROR] Failed to execute goal com.ning.maven.plugins:maven-dependency-versions-check-plugin:2.0.2:check (default) on project chat-service: While running mojo: Some problems were encountered while processing the POMs:
[ERROR] [ERROR] 'dependencies.dependency.systemPath' for com.oracle:coherence:jar must specify an absolute path but is ${project.basedir}/lib/coherence-3.7.1.5.jar @ line 268, column 25
```

I am able to use bucket4j by patching out Coherence support: https://github.com/vladimir-bukhtoyarov/bucket4j/compare/master...opentable:oracle-jars
but obviously maintaining my own release is not appealing.

A better solution might be to take your Coherence jar and use the `install:file` Maven target to include it in your repository.  Then you could use a `optional` or `provided` dependency so that downstream projects can use bucket4j without being polluted by Oracle crap :)

**Comment by vladimir-bukhtoyarov** [comment]
Hello @stevenschlansker,

I am agree with your arguments that ```system``` scope dependency involves a awkward. To solve this I have two plan:
- Long term: migrate to [JCache API](https://www.jcp.org/en/jsr/detail?id=107) and do not depend from concrete GRID solution at all. I think it is better choice, because this will provide ability to use many other products like Infinispan, Gemfire, Gygaspace, etc.
- Short term: to solve problem in 30 minutes I can just remove support of Coherence. It is should not affetcs any users because clients who use Buckets4j with coherence may continue use version 1.0.1. I am going to to this work today and release version 1.1, then release long term strategy in few weeks.

**Comment by vladimir-bukhtoyarov** [comment]
@stevenschlansker please comfirm that problem solved
```xml
<dependency>
    <groupId>com.github</groupId>
    <artifactId>bucket4j</artifactId>
    <version>1.1.0</version>
</dependency>
```

**Comment by stevenschlansker** [comment]
Yes, thank you for the quick fix!  I agree your plan makes sense.  So far your library seems very nice 😺
