### ISSUE TITLE
Add support for spring cache

### ISSUE THREAD

**Issue by lchayoun** [vladimir-bukhtoyarov/bucket4j#93]

**Comment by vladimir-bukhtoyarov** [comment]
@lchayoun please provide a description

**Comment by lchayoun** [comment]
We are using this library in [spring-cloud-zuul-ratelimit](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit) and I would like to use Spring Cache which wrap other caches instead of JCache directly.

It will be a lot of use since we will automatically get metrics on the configured cache and management by Spring

**Comment by vladimir-bukhtoyarov** [comment]
I am unable to find documentation related to spring cache. Is it a dedicated spring project? Or is it part of spring core?

**Comment by vladimir-bukhtoyarov** [comment]
@lchayoun 

```org.springframework.cache.Cache``` is part of "spring-context" module 
```xml
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context</artifactId>
</dependency>
```

After investigation of  [javadocs for Spring Cache](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/Cache.html) I have made the conclusion that from Bucket4j perspective the Spring Cache cannot be a replacement for ```JSR 107``` because Spring Cache does not provide the analog of [invoke](https://static.javadoc.io/javax.cache/cache-api/1.0.0/javax/cache/Cache.html#invoke) from ```JSR 107```. It is not surprising since Spring Cache is an abstraction for caching and does not try to solve the problems from the distributed computations domain. 

> It will be a lot of use since we will automatically get metrics on the configured cache and management by Spring

If you prefer to work with ```JSR 107``` providers via Spring API then you are free to do so, in order to eliminate the API mismatch you just need to downcast the spring cache to particular ```JSR 107``` provider via [getNativeCache](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/Cache.html#getNativeCache--).

**Comment by lchayoun** [comment]
Hi,

I'm not suggesting to replace it, I suggest to support both of them

**Comment by vladimir-bukhtoyarov** [comment]
```org.springframework.cache.Cache``` cannot be supported because of lack of its API, Spring Cache is not an abstraction for distributed computation.

**Comment by vladimir-bukhtoyarov** [comment]
According to ```com.github.benmanes.caffeine.cache.Cache```. 

It can be supported since ```caffeine``` provides all necessary functionality for mutual exclusion entry processing via [asMap](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L180) method. Also, I have tested compatibility with Caffeine via [production check list](https://github.com/vladimir-bukhtoyarov/bucket4j/blob/master/doc-pages/production-jcache-checklist.md#verification-of-compatibility-with-particular-jcache-provider-is-your-responsibility) and all works fine
```java
public static void main(String[] args) throws InterruptedException {
        String key = "42";
        Cache<String, Integer> cache = Caffeine.newBuilder().build();
        ConcurrentMap<String, Integer> consurrentMap = cache.asMap();
        consurrentMap.put(key, 0);


        int threads = 4;
        int iterations = 1000;
        consurrentMap.put(key, 0);
        CountDownLatch latch = new CountDownLatch(threads);
        for (int i = 0; i < threads; i++) {
            new Thread(() -> {
                try {
                    for (int j = 0; j < iterations; j++) {
                        consurrentMap.compute(key, (k, value) -> value + 1);
                        try {
                            Thread.sleep(10);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                } finally {
                    latch.countDown();
                }
            }).start();
        }
        latch.await();
        int value = consurrentMap.get(key);
        if (value == threads * iterations) {
            System.out.println("Implementation which you use is compatible with Bucket4j");
        } else {
            String msg = "Implementation which you use is not compatible with Bucket4j";
            msg += ", " + (threads * iterations - value) + " writes are missed";
            throw new IllegalStateException(msg);
        }
    }
```

So, if you want to have direct Caffeine support without [Caffeine JSR 107](https://github.com/ben-manes/caffeine/tree/master/jcache) interface, feel free to create dedicate issue. I will implement it eventually.
