### ISSUE TITLE
HazelcastSerializationException There is no suitable de-serializer for type 1.

### ISSUE THREAD

**Issue by jportner-hw** [vladimir-bukhtoyarov/bucket4j#99]
I'm getting this error when attempting to use bucket4j 4.4.1 + hazelcast 3.11.3

Any ideas?
```
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 1. This exception is likely to be caused by di
fferences in the serialization configuration between members or between clients and members.
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:238)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:182)
        at com.hazelcast.client.spi.ClientProxy.toObject(ClientProxy.java:102)
        at com.hazelcast.client.proxy.ClientMapProxy.executeOnKeyInternal(ClientMapProxy.java:1449)
        at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:1440)
        at io.github.bucket4j.grid.hazelcast.HazelcastProxy.execute(HazelcastProxy.java:46)
        at io.github.bucket4j.grid.GridBucket.execute(GridBucket.java:177)
        at io.github.bucket4j.grid.GridBucket.tryConsumeAndReturnRemainingTokensImpl(GridBucket.java:93)
        at io.github.bucket4j.AbstractBucket.tryConsumeAndReturnRemaining(AbstractBucket.java:346)
```

I have no special serialization configured in hazelcast. Other objects are able to be serialized/deserialized fine, its just bucket4j with which I have this problem.

**Comment by vladimir-bukhtoyarov** [comment]
@jportner-hw I am unable to reproduce deserialization problem via tests on version hazelcast 3.11.3. Please check that bucket4j-core/backet4j-jcache/bucket4j-hazelcast jars present in the classpath for all nodes in the cluster. If there is no problem with classpath then provide a [minimal&executable example](http://sscce.org/)  which reproduces the problem.

**Comment by yogenderyadavBP** [comment]
org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.lang.IllegalArgumentException: DefaultSerializer requires a Serializable payload but received an object of type [io.github.bucket4j.local.LockFreeBucket]
[Feb 10 2023 15:58:19 GMT+0530] postpe-uat-prod-6b8946488f-cqpdk:       at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:96)
[Feb 10 2023 15:58:19 GMT+0530] postpe-uat-prod-6b8946488f-cqpdk:       at org.springframework.data.redis.core.AbstractOperations.rawValue(AbstractOperations.java:127)
[Feb 10 2023 15:58:19 GMT+0530] postpe-uat-prod-6b8946488f-cqpdk:       at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:235)

Getting this error while setting bucket object in redis.

**Comment by vladimir-bukhtoyarov** [comment]
@yogenderyadavBP

You must not serialize instances of bucket directly, because library explicitly designed to disallow this. 

LockFreeBucket implements [LocalBucket](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java) interface, that declares two API for serialization:
* Binary API: [toBinarySnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L61) / [fromBinarySnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L72)
* Json friendly API: [toJsonCompatibleSnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L81) / [fromJsonCompatibleSnapshot](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/local/LocalBucket.java#L92)

So cast your bucket to LocalBucket and one of API that mentioneed above.
